### PR TITLE
Make geoCodeMarker optional

### PR DESCRIPTION
**Pull request by JonasKa**
Currently a L.Marker is always created and displayed when a geocode result i presented on the map.

The fitBounds functionality is, from my perspective, enough to visualize the result. It would be nice with an option, eg. showResultMarker: false

### CODE REVIEW

**Comment by sa3m** [comment]
Wow, that's a big pull request :)
I'm not sure I'll accept it, I don't think it's the same plugin now.
Thanks anyway.

**Comment by perliedman** [comment]
@JonasKa I think maybe you wanted to submit this PR to https://github.com/perliedman/leaflet-control-geocoder ?

**Comment by JonasKa** [comment]
@sa3m sorry about that. Just forget about it :)

@perliedman Yes, that's was my intention, but instead I created (two) here instead. No idea how that happend. I'll try make it right the next time.

//GitHub newbie

**Comment by JonasKa** [comment]
..I guess I forgot to change "base fork" during creation of the PR.

**Pull request closed without merging**
